name: phd-builder
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - langchain
      - langchain-huggingface
      - huggingface_hub
      - pydantic
      - requests
      - dotenv
